artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/InsiderCloud/summarizer-datasets/raw/main/dataset_samsum.zip
  local_data_file: artifacts/data_ingestion/samsum_dataset.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train","test","validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/dataset_samsum
  tokenizer_name: google/bigbird-pegasus-large-arxiv

